
dubbo:
  application:
    name: product-background
  registry:
    protocol: zookeeper
    address: 192.168.206.128:2181
server:
  port: 9090
spring:
  thymeleaf:
    cache: false
image:
  server: http://192.168.206.128/
fdfs:
    so-timeout: 1500
    connect-timeout: 600
    pool:
      jmx-enabled: false
    thumb-image:
      width: 100
      height: 100
    tracker-list: 192.168.206.128:22122