
dubbo:
  application:
    name: product-type-service
  registry:
    protocol: zookeeper
    address: 192.168.206.128:2181
  protocol:
    port: 28801
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///qf-v2
    username: root
    password: 123